# <center > Introduction to Probabilistic Graphical Models
## <center > Practical Session 1

### Students : Firas Omrane and Ahlem Jouidi

In [0]:
import numpy as np
import random

## Question 0 : 
 we can show that :
 
 $ \log \sum_{i=1}^{I} \exp v_i = a + \log \sum_{i=1}^{I} \exp v_i-a  $ 
 \\
 
For an arbitrary a. \\
This means, we can shift the center of the exponential sum.
we can take $ a= \max_{i} v_i$

In [3]:
def logSumExp(v) :
    a= np.max(v)
    return a+np.log(np.sum(np.exp(v-a)))

v=np.array([-1234,-1235])
logSumExp(v)

-1233.6867383124818

## Question 1

The robots can be in N positions in the circular corridor. \\
Let's denote : \\
$ x_k :$ position of the robot $ k \in {1..N} $ \\
$ y_k : $ the noisy observation of the robot at step k. \\
Initial probability $ \pi_i= \frac{1}{N} $ \\

It is a Hidden Markov Chain. 


In [4]:
print('The associated directed graphical model of this hidden markov chain :')
from IPython.display import display, Image, SVG, Math, YouTubeVideo
Image(url='https://imagizer.imageshack.com/img923/3069/WG04MN.png')

The associated directed graphical model of this hidden markov chain :


The transition model is : $$P(x_n=i/x_{n-1}=j) = A_{ij} $$
where $ A{ij} $ is the transition matrix. \\

The observation model is : $$ P(y_n/x_n)= w*\delta(y_n-x_n) - (1-w)*\mathcal{U}(1..N)$$

  where $ \delta $ is the dirac function \\
  $ \mathcal{U} $ is the uniform distribution 
  
  

The transition matrix $A=$
\begin{bmatrix}
\epsilon  & 0  & 0 & \cdots & \cdots & \cdots & \cdots & 1-\epsilon \\
1-\epsilon  & \epsilon  & 0  & \ddots & && & \vdots \\
0 & 1-\epsilon  & \epsilon & 0  & \ddots & &  & \vdots \\
\vdots & \ddots & \ddots & \ddots & \ddots & \ddots &  & \vdots \\
\vdots & & \ddots & \ddots & \ddots & \ddots & \ddots& \vdots\\
\vdots  & & & \ddots & 1-\epsilon  & \epsilon  &  0  & 0\\
\vdots  & && & \ddots & 1-\epsilon  & \epsilon  &  0\\
0 & \cdots &  \cdots & \cdots & \cdots & 0 & 1-\epsilon & \epsilon  \\
\end{bmatrix}

## Question 3

\usepackage{amsmath} \\


a) Distribution of the robot's current position given the observations so far :
$P(x_k|y_{1:k})$ \\

b) Distribution of the robot's position at time step k given all the observations : $P(x_k|y_{1:N})$ \\

c) Distribution of the robot's next position given the observations so far : $P(x_{k+1}|y_{1:k})$ \\

d) Distribution of the robot's next sensor reading given the observations so far : $P(y_{k+1}|y_{1:k})$ \\

e) Distribution of the robot's initial position given observations so far : $P(x_0|y_{1:k})$ \\

f) Most likely current position of the robot given the observations so far : $x^{*}= \operatorname*{argmax}_{x_k}P(x_k|y_{1:k})$ \\

g) Most likely trajectory taken by the robot from the start until now given the observations so far : $ (x_1^{*},x_2^{*},..,x_k^{*}) = \operatorname*{argmax}_{x_k}P(x_{1:k}|y_{1:k})$


## Question 4

In [0]:
## The value returned by the sensor : P=w right step
##                                    P=1-w wrong step
def predictY(i):
    positions=np.arange(N)
    positions=np.delete(positions, i)
    other=np.random.choice(positions,1)
    y=np.random.choice([i,other],1,p=[w,1-w])
    return int(y)

In [6]:
N=50
K=100
epsilon=0.3
w=0.8

#First step and first value returned by the sensor
x_0=random.randint(0,N)
y_0=predictY(x_0)

X=[x_0]
Y=[y_0]

#Generation of the sequence of steps and values returned by the sensor
x=int(x_0)
for i in range(1,K):
    if x==N-1 :
        x=int(np.random.choice([x,0],1,p=[epsilon,1-epsilon]))
    else :
        x=int(np.random.choice([x,x+1],1,p=[epsilon,1-epsilon]))

    X.append(x)
    y=predictY(x)
    Y.append(y)
  
  
print('The sequence of steps is :')
print(X)
print('The sequence of values returned by the sensor is ')
print(Y)
  

The sequence of steps is :
[34, 35, 35, 36, 37, 38, 39, 39, 39, 39, 39, 39, 40, 40, 41, 42, 42, 43, 43, 43, 43, 44, 45, 45, 45, 46, 47, 47, 47, 48, 48, 49, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 11, 12, 13, 14, 14, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 24, 24, 24, 25, 26, 27, 28, 29, 30, 31, 31, 32, 33, 33, 34, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 44, 45, 46, 46, 47, 48, 49, 49, 0, 1, 2, 2, 2, 2]
The sequence of values returned by the sensor is 
[34, 35, 35, 36, 37, 38, 39, 39, 39, 39, 39, 39, 40, 40, 41, 42, 42, 43, 43, 43, 43, 44, 45, 45, 45, 46, 47, 47, 47, 48, 48, 49, 0, 1, 2, 3, 4, 5, 6, 22, 8, 9, 21, 10, 11, 12, 13, 14, 14, 14, 9, 16, 17, 31, 19, 20, 21, 14, 23, 24, 24, 24, 24, 25, 26, 23, 28, 29, 30, 31, 27, 32, 33, 33, 15, 34, 35, 36, 37, 38, 39, 40, 41, 39, 31, 44, 44, 27, 46, 37, 12, 48, 36, 49, 0, 1, 2, 30, 2, 2]


In [7]:
#Definition of the transition matrix
A=np.zeros((N,N))
for i in range(N):
    A[i,i]=epsilon
    A[i,i-1]=1-epsilon
print('The transition matrix A =')
print(A)

B=np.ones((N,N))
for i in range(N):
    for j in range(N):
        if i==j:
            B[i,i]=w-(1-w)*1/N
        else :
            B[i,j]=(1-w)*1/N
print(B)
#The initial probaility vector Pi
pi=np.ones(N)*1/N
print('The initial probabilities vector Pi =')
print(pi)

The transition matrix A =
[[0.3 0.  0.  ... 0.  0.  0.7]
 [0.7 0.3 0.  ... 0.  0.  0. ]
 [0.  0.7 0.3 ... 0.  0.  0. ]
 ...
 [0.  0.  0.  ... 0.3 0.  0. ]
 [0.  0.  0.  ... 0.7 0.3 0. ]
 [0.  0.  0.  ... 0.  0.7 0.3]]
[[0.796 0.004 0.004 ... 0.004 0.004 0.004]
 [0.004 0.796 0.004 ... 0.004 0.004 0.004]
 [0.004 0.004 0.796 ... 0.004 0.004 0.004]
 ...
 [0.004 0.004 0.004 ... 0.796 0.004 0.004]
 [0.004 0.004 0.004 ... 0.004 0.796 0.004]
 [0.004 0.004 0.004 ... 0.004 0.004 0.796]]
The initial probabilities vector Pi =
[0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02]


In [0]:
def logSumExp(v,A):
    a=max(v)
    return a+np.log(A @ np.exp(v - a))



In [0]:
def forward(k, i, X):
    if (i==0):
        return np.log(np.ones(N)/N)
    elif(k == i):
        return np.log(B[X[i-1] - 1,:]) + forward(k,i-1, X)
    else :
        return logSumExp(forward(k-1, i, X),A)     
 
   
  

In [0]:

def backward(k,i, X):

    if (i == len(X)+1):
        return np.zeros(np.shape(A)[0])
    elif (k == i):
        return np.log(B[:,X[i-1] - 1]) + backward(k,i+1,X)
    else :
        return logSumExp(backward(k+1, i,X),A.T)
        
  
   

In [0]:
def TotalDistri(X,k ):
    N=len(X)
    z= np.exp(forward(N,N,X)) 
    forw = forward(k,k,X)
    backw  = backward(k, k+1, X)
    return np.exp(forw + backw)/np.sum(z)
        

In [12]:
K=100
dist_Robot =  TotalDistri(X,K)
print(dist_Robot)
print ("The sum of the probabilities  ")
print(np.sum(dist_Robot))  

[2.74165807e-010 9.88215565e-001 1.16456320e-002 1.37217435e-004
 1.58498025e-006 2.33465940e-015 3.43893500e-024 1.00803630e-030
 1.20225672e-055 7.00880922e-060 2.05444998e-066 2.34573357e-084
 2.71723706e-086 2.65275558e-088 3.98769432e-113 3.70694536e-115
 1.37910949e-121 6.37216069e-119 2.94395582e-116 1.36010790e-113
 6.28369857e-111 2.90306874e-108 1.34121776e-105 4.01221344e-096
 2.20943943e-093 1.03612173e-090 4.79118402e-088 2.21361486e-085
 1.02269146e-082 4.72483472e-080 3.75643730e-075 1.99689663e-072
 1.62785053e-067 1.51909902e-062 7.89970598e-060 3.67434264e-057
 1.69798774e-054 7.84476003e-052 3.62427969e-049 1.67441722e-046
 7.73580756e-044 3.57394309e-041 1.65116171e-038 1.42229547e-033
 7.03312966e-031 6.16356774e-026 3.00493140e-023 1.39011421e-020
 1.24020638e-015 5.93127153e-013]
The sum of the probabilities  
0.9999999999999999


## Question 6

The new transition matrix $A=$
\begin{bmatrix}
(1-K)\epsilon +\frac{K}{N}  & \frac{K}{N}  & \frac{K}{N} & \cdots & \cdots & \cdots & \cdots & (1-K)(1-\epsilon) + \frac{K}{N} \\
(1-K)(1-\epsilon) + \frac{K}{N}  & (1-K)\epsilon +\frac{K}{N}  & \frac{K}{N} & \ddots & && & \vdots \\
\frac{K}{N} & (1-K)(1-\epsilon) + \frac{K}{N}  & (1-K)\epsilon +\frac{K}{N} & \frac{K}{N}  & \ddots & &  & \vdots \\
\vdots & \ddots & \ddots & \ddots & \ddots & \ddots &  & \vdots \\
\vdots & & \ddots & \ddots & \ddots & \ddots & \ddots& \vdots\\
\vdots  & & & \ddots & (1-K)(1-\epsilon) + \frac{K}{N}  & (1-K)\epsilon + \frac{K}{N}  &  \frac{K}{N}  & \frac{K}{N}\\
\vdots  & && & \ddots & (1-K)(1-\epsilon) + \frac{K}{N}  & (1-K)\epsilon + \frac{K}{N}  &  \\
\frac{K}{N} & \cdots &  \cdots & \cdots & \cdots & 0 & (1-K)(1-\epsilon) + \frac{K}{N} & (1-K)\epsilon + \frac{K}{N}  \\
\end{bmatrix}

We can reuse the same code since only the transition matrix would be modified

In [13]:
K = 0.1
A=K/N*np.ones((N,N))
for i in range(N):
    A[i,i]+=(1-K)*epsilon
    A[i,i-1]+= (1-K)*(1-epsilon) 
print('The new transition matrix A =')
print(A)
B=np.ones((N,N))
for i in range(N):
    for j in range(N):
        if i==j:
            B[i,i]=w-(1-w)*1/N
        else :
            B[i,j]=(1-w)*1/N
print('\n The observation matrix B: ')
print(B)
#The initial probaility vector Pi
pi=np.ones(N)*1/N
print('\n The initial probabilities vector Pi =')
print(pi)

The new transition matrix A =
[[0.272 0.002 0.002 ... 0.002 0.002 0.632]
 [0.632 0.272 0.002 ... 0.002 0.002 0.002]
 [0.002 0.632 0.272 ... 0.002 0.002 0.002]
 ...
 [0.002 0.002 0.002 ... 0.272 0.002 0.002]
 [0.002 0.002 0.002 ... 0.632 0.272 0.002]
 [0.002 0.002 0.002 ... 0.002 0.632 0.272]]

 The observation matrix B: 
[[0.796 0.004 0.004 ... 0.004 0.004 0.004]
 [0.004 0.796 0.004 ... 0.004 0.004 0.004]
 [0.004 0.004 0.796 ... 0.004 0.004 0.004]
 ...
 [0.004 0.004 0.004 ... 0.796 0.004 0.004]
 [0.004 0.004 0.004 ... 0.004 0.796 0.004]
 [0.004 0.004 0.004 ... 0.004 0.004 0.796]]

 The initial probabilities vector Pi =
[0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02
 0.02 0.02 0.02 0.02 0.02 0.02 0.02 0.02]


In [14]:
K=100
dist_Robot =  TotalDistri(X,K)
print(dist_Robot)
print ("The sum of the probabilities ")
print(np.sum(dist_Robot))  

[3.75666083e-05 9.86486082e-01 1.15742810e-02 1.72471524e-04
 3.91132918e-05 3.75663416e-05 3.75663416e-05 3.75663416e-05
 3.75663416e-05 3.75663416e-05 3.75663416e-05 3.75663416e-05
 3.75663416e-05 3.75663416e-05 3.75663416e-05 3.75663416e-05
 3.75663416e-05 3.75663416e-05 3.75663416e-05 3.75663416e-05
 3.75663416e-05 3.75663416e-05 3.75663416e-05 3.75663416e-05
 3.75663416e-05 3.75663416e-05 3.75663416e-05 3.75663416e-05
 3.75663416e-05 3.75663416e-05 3.75663416e-05 3.75663416e-05
 3.75663416e-05 3.75663416e-05 3.75663416e-05 3.75663416e-05
 3.75663416e-05 3.75663416e-05 3.75663416e-05 3.75663416e-05
 3.75663416e-05 3.75663416e-05 3.75663416e-05 3.75663416e-05
 3.75663416e-05 3.75663416e-05 3.75663416e-05 3.75663416e-05
 3.75663416e-05 3.75663422e-05]
The sum of the probabilities 
1.0
